// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4qbn0gV0BrTCDUn0WRFVs7ZOVAXBXttU',
    appId: '1:959780080750:web:e4c0cf7b2d3fcb45ffaa7f',
    messagingSenderId: '959780080750',
    projectId: 'flipr-aa040',
    authDomain: 'flipr-aa040.firebaseapp.com',
    storageBucket: 'flipr-aa040.appspot.com',
    measurementId: 'G-G3Y2CKY3M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlq5E2c48RZKSkTWY0vjBnP1fFsqP0EjY',
    appId: '1:959780080750:android:5f6517fcaa0f7d4cffaa7f',
    messagingSenderId: '959780080750',
    projectId: 'flipr-aa040',
    storageBucket: 'flipr-aa040.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHjLbZ0tqfmBZCJfwIl-81KCqJuxQA5Q',
    appId: '1:959780080750:ios:f366b0e160e36df6ffaa7f',
    messagingSenderId: '959780080750',
    projectId: 'flipr-aa040',
    storageBucket: 'flipr-aa040.appspot.com',
    iosClientId: '959780080750-gsuc1ifpaaajj9riageqnc0a5v820dre.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHjLbZ0tqfmBZCJfwIl-81KCqJuxQA5Q',
    appId: '1:959780080750:ios:d81a1d34b58d3f60ffaa7f',
    messagingSenderId: '959780080750',
    projectId: 'flipr-aa040',
    storageBucket: 'flipr-aa040.appspot.com',
    iosClientId: '959780080750-jdms9htp55937bb740lun400jl4f4stu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipr.RunnerTests',
  );
}
